version: '3.8'

services:
  web:
    container_name: django_PPS
    build: .
    image: django_image_pps
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/blog/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on: 
      - db
  db:
    container_name: Postgre_sql_prod
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/blog/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
